app:
  title: Tigre Backstage App
  baseUrl: http://localhost:7007

organization:
  name: Tigre do Mexico

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:7007
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  auth:
    keys:
      - secret: ${BACKEND_SECRET}
  database:
    client: pg
    connection:
      host: backstage-db
      port: 5432
      user: postgres
      password: Postgres2022!

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN_CLASSIC}

proxy:
  endpoints:
    '/test':
      target: 'https://example.com'
      changeOrigin: true

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'

auth:
  providers:
    github:
      development:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName

scaffolder:
  github:
    token: ${GITHUB_TOKEN_CLASSIC}
    visibility: public

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Domain, Template]
  locations:
    - type: url
      target: https://github.com/TigreDoMexico/project-backstage-data/blob/main/domain/personalprojects-domain.yaml
      rules:
        - allow: [Domain]
    - type: url
      target: https://github.com/TigreDoMexico/project-backstage-data/blob/main/system/quizz-system.yaml
      rules:
        - allow: [System]
    - type: url
      target: https://github.com/TigreDoMexico/project-backstage-data/blob/main/system/birthday-manager-system.yaml
      rules:
        - allow: [System]
    - type: url
      target: https://github.com/TigreDoMexico/project-backstage-data/blob/main/system/study-system.yaml
      rules:
        - allow: [System]
    - type: url
      target: https://github.com/TigreDoMexico/project-backstage-data/blob/main/groups/backstage-group.yaml
      rules:
        - allow: [User, Group]
    - type: url
      target: https://github.com/TigreDoMexico/project-backstage-data/blob/main/templates/remote-templates.yaml
      rules:
        - allow: [Template]
