apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  BACKEND_SECRET: secretback
  GITHUB_TOKEN_CLASSIC: secrettoken
  GITHUB_CLIENT_ID: secretclientid
  GITHUB_CLIENT_SECRET: secretclient